UPDATE questions SET image_url = '/images/60계 간지치킨.jpg' WHERE content = '60계 간지치킨';
UPDATE questions SET image_url = '/images/BBQ 자메이카.jpg' WHERE content = 'BBQ 자메이카';
UPDATE questions SET image_url = '/images/BBQ 황금올리브.jpg' WHERE content = 'BBQ 황금올리브';
UPDATE questions SET image_url = '/images/BHC 맛초킹.jpg' WHERE content = 'BHC 맛초킹';
UPDATE questions SET image_url = '/images/BHC 뿌링클.avif' WHERE content = 'BHC 뿌링클';
UPDATE questions SET image_url = '/images/covers' WHERE content = 'covers';
UPDATE questions SET image_url = '/images/desktop.ini' WHERE content = 'desktop';
UPDATE questions SET image_url = '/images/KFC 핫크리스피.jpg' WHERE content = 'KFC 핫크리스피';
UPDATE questions SET image_url = '/images/가을.jpg' WHERE content = '가을';
UPDATE questions SET image_url = '/images/간짬뽕.jpg' WHERE content = '간짬뽕';
UPDATE questions SET image_url = '/images/감자면.webp' WHERE content = '감자면';
UPDATE questions SET image_url = '/images/강철의 연금술사.jpg' WHERE content = '강철의 연금술사';
UPDATE questions SET image_url = '/images/강호동.jpg' WHERE content = '강호동';
UPDATE questions SET image_url = '/images/검정고무신.jpg' WHERE content = '검정고무신';
UPDATE questions SET image_url = '/images/공유.jpg' WHERE content = '공유';
UPDATE questions SET image_url = '/images/공화춘.jpg' WHERE content = '공화춘';
UPDATE questions SET image_url = '/images/교촌 레드콤보.png' WHERE content = '교촌 레드콤보';
UPDATE questions SET image_url = '/images/교촌 허니콤보.png' WHERE content = '교촌 허니콤보';
UPDATE questions SET image_url = '/images/굽네 고추바사삭.webp' WHERE content = '굽네 고추바사삭';
UPDATE questions SET image_url = '/images/굽네 볼케이노.jpg' WHERE content = '굽네 볼케이노';
UPDATE questions SET image_url = '/images/귀멸의 칼날.jpg' WHERE content = '귀멸의 칼날';
UPDATE questions SET image_url = '/images/그리스.png' WHERE content = '그리스';
UPDATE questions SET image_url = '/images/김고은.jpg' WHERE content = '김고은';
UPDATE questions SET image_url = '/images/김수현.jpg' WHERE content = '김수현';
UPDATE questions SET image_url = '/images/김종국.jpg' WHERE content = '김종국';
UPDATE questions SET image_url = '/images/김채원.jpg' WHERE content = '김채원';
UPDATE questions SET image_url = '/images/김혜수.jpg' WHERE content = '김혜수';
UPDATE questions SET image_url = '/images/깐부치킨.webp' WHERE content = '깐부치킨';
UPDATE questions SET image_url = '/images/꼬꼬면.webp' WHERE content = '꼬꼬면';
UPDATE questions SET image_url = '/images/나가사끼 짬뽕.webp' WHERE content = '나가사끼 짬뽕';
UPDATE questions SET image_url = '/images/나루토.png' WHERE content = '나루토';
UPDATE questions SET image_url = '/images/나연.jpg' WHERE content = '나연';
UPDATE questions SET image_url = '/images/남아프리카 공화국.png' WHERE content = '남아프리카 공화국';
UPDATE questions SET image_url = '/images/남자라면.webp' WHERE content = '남자라면';
UPDATE questions SET image_url = '/images/너구리.webp' WHERE content = '너구리';
UPDATE questions SET image_url = '/images/네네 스노윙.jpg' WHERE content = '네네 스노윙';
UPDATE questions SET image_url = '/images/네네 파닭.jpg' WHERE content = '네네 파닭';
UPDATE questions SET image_url = '/images/네덜란드.png' WHERE content = '네덜란드';
UPDATE questions SET image_url = '/images/노랑통닭 알싸한마늘.png' WHERE content = '노랑통닭 알싸한마늘';
UPDATE questions SET image_url = '/images/노랑통닭 후라이드.jpg' WHERE content = '노랑통닭 후라이드';
UPDATE questions SET image_url = '/images/닝닝.jpg' WHERE content = '닝닝';
UPDATE questions SET image_url = '/images/다니엘.jpg' WHERE content = '다니엘';
UPDATE questions SET image_url = '/images/대한민국.png' WHERE content = '대한민국';
UPDATE questions SET image_url = '/images/데스노트.jpg' WHERE content = '데스노트';
UPDATE questions SET image_url = '/images/덴마크.png' WHERE content = '덴마크';
UPDATE questions SET image_url = '/images/도라에몽.webp' WHERE content = '도라에몽';
UPDATE questions SET image_url = '/images/독일.png' WHERE content = '독일';
UPDATE questions SET image_url = '/images/둘둘치킨.jpg' WHERE content = '둘둘치킨';
UPDATE questions SET image_url = '/images/드래곤볼.jpg' WHERE content = '드래곤볼';
UPDATE questions SET image_url = '/images/디지몬 어드벤처.jpg' WHERE content = '디지몬 어드벤처';
UPDATE questions SET image_url = '/images/또래오래 갈릭반핫양념반.jpg' WHERE content = '또래오래 갈릭반핫양념반';
UPDATE questions SET image_url = '/images/러시아.png' WHERE content = '러시아';
UPDATE questions SET image_url = '/images/로제.jpg' WHERE content = '로제';
UPDATE questions SET image_url = '/images/리사.jpg' WHERE content = '리사';
UPDATE questions SET image_url = '/images/리즈.jpg' WHERE content = '리즈';
UPDATE questions SET image_url = '/images/마동석.jpg' WHERE content = '마동석';
UPDATE questions SET image_url = '/images/멕시카나 땡초.jpg' WHERE content = '멕시카나 땡초';
UPDATE questions SET image_url = '/images/멕시코.png' WHERE content = '멕시코';
UPDATE questions SET image_url = '/images/멸치칼국수.webp' WHERE content = '멸치칼국수';
UPDATE questions SET image_url = '/images/명탐정 코난.png' WHERE content = '명탐정 코난';
UPDATE questions SET image_url = '/images/모모.jpg' WHERE content = '모모';
UPDATE questions SET image_url = '/images/무파마.webp' WHERE content = '무파마';
UPDATE questions SET image_url = '/images/미국.png' WHERE content = '미국';
UPDATE questions SET image_url = '/images/미연.jpg' WHERE content = '미연';
UPDATE questions SET image_url = '/images/민지.jpg' WHERE content = '민지';
UPDATE questions SET image_url = '/images/바른치킨 대새레드.jpg' WHERE content = '바른치킨 대새레드';
UPDATE questions SET image_url = '/images/박보검.jpg' WHERE content = '박보검';
UPDATE questions SET image_url = '/images/박서준.jpg' WHERE content = '박서준';
UPDATE questions SET image_url = '/images/베트남.png' WHERE content = '베트남';
UPDATE questions SET image_url = '/images/벨기에.png' WHERE content = '벨기에';
UPDATE questions SET image_url = '/images/보드람 치킨.jpg' WHERE content = '보드람 치킨';
UPDATE questions SET image_url = '/images/봇치 더 락.jpg' WHERE content = '봇치 더 락';
UPDATE questions SET image_url = '/images/부어치킨 크리스피.jpg' WHERE content = '부어치킨 크리스피';
UPDATE questions SET image_url = '/images/불닭 까르보.webp' WHERE content = '불닭 까르보';
UPDATE questions SET image_url = '/images/불닭볶음면.webp' WHERE content = '불닭볶음면';
UPDATE questions SET image_url = '/images/브라질.png' WHERE content = '브라질';
UPDATE questions SET image_url = '/images/블리치.jpg' WHERE content = '블리치';
UPDATE questions SET image_url = '/images/비빔면 배홍동.webp' WHERE content = '비빔면 배홍동';
UPDATE questions SET image_url = '/images/사나.jpg' WHERE content = '사나';
UPDATE questions SET image_url = '/images/사리곰탕면.webp' WHERE content = '사리곰탕면';
UPDATE questions SET image_url = '/images/사우디아라비아.png' WHERE content = '사우디아라비아';
UPDATE questions SET image_url = '/images/사쿠라.jpg' WHERE content = '사쿠라';
UPDATE questions SET image_url = '/images/삼양라면.webp' WHERE content = '삼양라면';
UPDATE questions SET image_url = '/images/새우탕.webp' WHERE content = '새우탕';
UPDATE questions SET image_url = '/images/설윤.jpg' WHERE content = '설윤';
UPDATE questions SET image_url = '/images/세일러문.jpg' WHERE content = '세일러문';
UPDATE questions SET image_url = '/images/센과 치히로의 행방불명.jpg' WHERE content = '센과 치히로의 행방불명';
UPDATE questions SET image_url = '/images/손석구.jpg' WHERE content = '손석구';
UPDATE questions SET image_url = '/images/손예진.jpg' WHERE content = '손예진';
UPDATE questions SET image_url = '/images/송중기.jpg' WHERE content = '송중기';
UPDATE questions SET image_url = '/images/송혜교.jpg' WHERE content = '송혜교';
UPDATE questions SET image_url = '/images/수지.jpg' WHERE content = '수지';
UPDATE questions SET image_url = '/images/스낵면.webp' WHERE content = '스낵면';
UPDATE questions SET image_url = '/images/스웨덴.png' WHERE content = '스웨덴';
UPDATE questions SET image_url = '/images/스위스.png' WHERE content = '스위스';
UPDATE questions SET image_url = '/images/스파이 패밀리.jpg' WHERE content = '스파이 패밀리';
UPDATE questions SET image_url = '/images/스페인.png' WHERE content = '스페인';
UPDATE questions SET image_url = '/images/슬기.jpg' WHERE content = '슬기';
UPDATE questions SET image_url = '/images/슬램덩크.jpg' WHERE content = '슬램덩크';
UPDATE questions SET image_url = '/images/신동엽.jpg' WHERE content = '신동엽';
UPDATE questions SET image_url = '/images/신라면 블랙.webp' WHERE content = '신라면 블랙';
UPDATE questions SET image_url = '/images/신라면.webp' WHERE content = '신라면';
UPDATE questions SET image_url = '/images/싸이.jpg' WHERE content = '싸이';
UPDATE questions SET image_url = '/images/썬더치킨.jpg' WHERE content = '썬더치킨';
UPDATE questions SET image_url = '/images/아기공룡 둘리.jpg' WHERE content = '아기공룡 둘리';
UPDATE questions SET image_url = '/images/아따맘마.jpg' WHERE content = '아따맘마';
UPDATE questions SET image_url = '/images/아르헨티나.png' WHERE content = '아르헨티나';
UPDATE questions SET image_url = '/images/아이린.jpg' WHERE content = '아이린';
UPDATE questions SET image_url = '/images/아이유.jpg' WHERE content = '아이유';
UPDATE questions SET image_url = '/images/안성탕면.webp' WHERE content = '안성탕면';
UPDATE questions SET image_url = '/images/안유진.jpg' WHERE content = '안유진';
UPDATE questions SET image_url = '/images/열라면.webp' WHERE content = '열라면';
UPDATE questions SET image_url = '/images/영국.png' WHERE content = '영국';
UPDATE questions SET image_url = '/images/예지.jpg' WHERE content = '예지';
UPDATE questions SET image_url = '/images/오빠닭.png' WHERE content = '오빠닭';
UPDATE questions SET image_url = '/images/오징어짬뽕.webp' WHERE content = '오징어짬뽕';
UPDATE questions SET image_url = '/images/왕뚜껑.webp' WHERE content = '왕뚜껑';
UPDATE questions SET image_url = '/images/원펀맨.jpg' WHERE content = '원펀맨';
UPDATE questions SET image_url = '/images/원피스.jpg' WHERE content = '원피스';
UPDATE questions SET image_url = '/images/웬디.jpg' WHERE content = '웬디';
UPDATE questions SET image_url = '/images/윈터.jpg' WHERE content = '윈터';
UPDATE questions SET image_url = '/images/유나.jpg' WHERE content = '유나';
UPDATE questions SET image_url = '/images/유재석.jpg' WHERE content = '유재석';
UPDATE questions SET image_url = '/images/육개장 사발면.webp' WHERE content = '육개장 사발면';
UPDATE questions SET image_url = '/images/은채.jpg' WHERE content = '은채';
UPDATE questions SET image_url = '/images/은혼.jpg' WHERE content = '은혼';
UPDATE questions SET image_url = '/images/이병헌.jpg' WHERE content = '이병헌';
UPDATE questions SET image_url = '/images/이수근.jpg' WHERE content = '이수근';
UPDATE questions SET image_url = '/images/이웃집 토토로.jpg' WHERE content = '이웃집 토토로';
UPDATE questions SET image_url = '/images/이정재.jpg' WHERE content = '이정재';
UPDATE questions SET image_url = '/images/이집트.png' WHERE content = '이집트';
UPDATE questions SET image_url = '/images/이탈리아.png' WHERE content = '이탈리아';
UPDATE questions SET image_url = '/images/이효리.jpg' WHERE content = '이효리';
UPDATE questions SET image_url = '/images/인도.png' WHERE content = '인도';
UPDATE questions SET image_url = '/images/일본.png' WHERE content = '일본';
UPDATE questions SET image_url = '/images/임영웅.jpg' WHERE content = '임영웅';
UPDATE questions SET image_url = '/images/자담 맵슐랭.png' WHERE content = '자담 맵슐랭';
UPDATE questions SET image_url = '/images/장원영.jpg' WHERE content = '장원영';
UPDATE questions SET image_url = '/images/전지현.jpg' WHERE content = '전지현';
UPDATE questions SET image_url = '/images/정우성.jpg' WHERE content = '정우성';
UPDATE questions SET image_url = '/images/제니.jpg' WHERE content = '제니';
UPDATE questions SET image_url = '/images/조이.jpg' WHERE content = '조이';
UPDATE questions SET image_url = '/images/주술회전.jpg' WHERE content = '주술회전';
UPDATE questions SET image_url = '/images/중국.png' WHERE content = '중국';
UPDATE questions SET image_url = '/images/지드래곤.jpg' WHERE content = '지드래곤';
UPDATE questions SET image_url = '/images/지수.jpg' WHERE content = '지수';
UPDATE questions SET image_url = '/images/지코바 숯불양념.jpg' WHERE content = '지코바 숯불양념';
UPDATE questions SET image_url = '/images/지효.jpg' WHERE content = '지효';
UPDATE questions SET image_url = '/images/진격의 거인.jpg' WHERE content = '진격의 거인';
UPDATE questions SET image_url = '/images/진라면 매운맛.avif' WHERE content = '진라면 매운맛';
UPDATE questions SET image_url = '/images/진라면 순한맛.webp' WHERE content = '진라면 순한맛';
UPDATE questions SET image_url = '/images/진짬뽕.webp' WHERE content = '진짬뽕';
UPDATE questions SET image_url = '/images/짜왕.webp' WHERE content = '짜왕';
UPDATE questions SET image_url = '/images/짜파게티.webp' WHERE content = '짜파게티';
UPDATE questions SET image_url = '/images/짱구는 못말려.jpg' WHERE content = '짱구는 못말려';
UPDATE questions SET image_url = '/images/차은우.jpg' WHERE content = '차은우';
UPDATE questions SET image_url = '/images/참깨라면.webp' WHERE content = '참깨라면';
UPDATE questions SET image_url = '/images/처갓집 슈프림양념.jpg' WHERE content = '처갓집 슈프림양념';
UPDATE questions SET image_url = '/images/체인소 맨.jpg' WHERE content = '체인소 맨';
UPDATE questions SET image_url = '/images/최민식.jpg' WHERE content = '최민식';
UPDATE questions SET image_url = '/images/최애의 아이.jpg' WHERE content = '최애의 아이';
UPDATE questions SET image_url = '/images/치킨마루.jpg' WHERE content = '치킨마루';
UPDATE questions SET image_url = '/images/카리나.jpg' WHERE content = '카리나';
UPDATE questions SET image_url = '/images/캐나다.png' WHERE content = '캐나다';
UPDATE questions SET image_url = '/images/태국.png' WHERE content = '태국';
UPDATE questions SET image_url = '/images/태연.jpg' WHERE content = '태연';
UPDATE questions SET image_url = '/images/튀김우동.webp' WHERE content = '튀김우동';
UPDATE questions SET image_url = '/images/튀르키예.png' WHERE content = '튀르키예';
UPDATE questions SET image_url = '/images/틈새라면.webp' WHERE content = '틈새라면';
UPDATE questions SET image_url = '/images/팔도비빔면.webp' WHERE content = '팔도비빔면';
UPDATE questions SET image_url = '/images/페리카나 양념.jpg' WHERE content = '페리카나 양념';
UPDATE questions SET image_url = '/images/포르투갈.png' WHERE content = '포르투갈';
UPDATE questions SET image_url = '/images/포켓몬스터.jpg' WHERE content = '포켓몬스터';
UPDATE questions SET image_url = '/images/폴란드.png' WHERE content = '폴란드';
UPDATE questions SET image_url = '/images/푸라닭 고추마요.jpg' WHERE content = '푸라닭 고추마요';
UPDATE questions SET image_url = '/images/푸라닭 블랙알리오.jpg' WHERE content = '푸라닭 블랙알리오';
UPDATE questions SET image_url = '/images/프랑스.png' WHERE content = '프랑스';
UPDATE questions SET image_url = '/images/하니.jpg' WHERE content = '하니';
UPDATE questions SET image_url = '/images/하울의 움직이는 성.jpg' WHERE content = '하울의 움직이는 성';
UPDATE questions SET image_url = '/images/하이큐.jpg' WHERE content = '하이큐';
UPDATE questions SET image_url = '/images/하정우.jpg' WHERE content = '하정우';
UPDATE questions SET image_url = '/images/해린.jpg' WHERE content = '해린';
UPDATE questions SET image_url = '/images/헌터x헌터.jpg' WHERE content = '헌터x헌터';
UPDATE questions SET image_url = '/images/현빈.jpg' WHERE content = '현빈';
UPDATE questions SET image_url = '/images/호식이 두마리.jpg' WHERE content = '호식이 두마리';
UPDATE questions SET image_url = '/images/호주.png' WHERE content = '호주';
UPDATE questions SET image_url = '/images/호치킨.jpg' WHERE content = '호치킨';
UPDATE questions SET image_url = '/images/황정민.jpg' WHERE content = '황정민';